### ISSUE TITLE
Copyright in production build

### ISSUE THREAD

**Issue by astrauka** [JedWatson/classnames#104]
Hey @JedWatson,
I am using webpack, once I compile production assets with
`NODE_ENV=production webpack -p --config webpack.client.config.js`,
I see the library copyright in javascript
![image](https://cloud.githubusercontent.com/assets/1308928/20798921/3f9c8196-b7e9-11e6-9521-c89a4d6618bc.png)

Is there a way to get rid of it?

**Comment by JedWatson** [comment]
Hi @astrauka,

This was added explicitly in response to #28 so that the license is preserved when you ship classnames with your app.

I believe this is similar to other packages you may include with licenses (e.g. React, etc)

According to the license, you must preserve the copyright when including the code in your app, however if you handle this separately with regards to crediting OSS packages in your project I'm happy for you to deal with that however you like for minified code :)

However, this is code that's taken a nontrivial amount of time to develop & maintain so I do appreciate the credit as a minimum in return.

**Comment by astrauka** [comment]
Thank you for the answer :) what I just noticed is that I am separating code to vendor and app bundles and all the libs should go to bundle, but classnames got into app. So that was the actual issue. Will profile produced JS to figure out how to put the package next to other vendor assets.
