### ISSUE TITLE
Warn if classname is undefined

### ISSUE THREAD

**Issue by InsOpDe** [JedWatson/classnames#222]
It would be good if one can toggle a flag which then outputs warnings if input-class names are `undefined`
Would help with refactoring and debugging

**Comment by dcousens** [comment]
@InsOpDe maybe for insight into how we could improve the package,  why is `undefined` problematic and something you want to eliminate?

**Comment by InsOpDe** [comment]
Consider following use-case:
```css
# styles.module.css
.some-class {
  color: red;
}
```
```typescript
import styles from "styles.module.css"
import cn from "classnames"
const SomeComponent = () => {
  return (
    <span
      classname={cn(styles.someClass)}
    >
      Im should be red but I am not
    </span>
    )
}
```
webpack et al renames the classnames from kebab-case to camelCase if is configured to do so.

If it is not, however, `styles.someClass` would yield `undefined`, instead of `some-class`. If I then would get a warning that `classnames` received `undefined` I would know that there is something wrong with my `key` instead of something with my `css`

Other than that I would think that receiving `undefined` as resolved classname string is never desirable

**Comment by dcousens** [comment]
@remcohaszing thoughts?
I think,  like in https://github.com/JedWatson/classnames/issues/239,  these are undesirable types,  but, the JS should probably only be defensive (ignoring them),  while the typescript types could be strict?

**Comment by remcohaszing** [comment]
I get where this issue is coming from. I use CSS modules myself. However, this is a problem of CSS modules, not `classnames`.

I consider accepting values to be a very useful feature of this package. A practical example:

```ts
import classNames from 'classnames';
import styles from './index.module.css';

interface ButtonProps {
  className?: string;
}

export function Button({ className }: ButtonProps) {
  return <button className={classNames(styles.button, className)} />;
}
```

It’s desirable to ensure `styles.button` is defined, but not to check `className`. In TypeScript strict mode the type of `className` is `string | undefined`, meaning `classnames` should also accept `undefined` in its type definitions.

This problem requires a solution such as [`eslint-plugin-css-modules`](https://github.com/atfzl/eslint-plugin-css-modules) (which is unmaintained).

**Comment by InsOpDe** [comment]
You are absolutely correct. I didnt consider this use-case

**Comment by dcousens** [comment]
💯 ,  thanks for reminding us @remcohaszing that `undefined` is truly first class in the module's usage.
