### ISSUE TITLE
why not merge this into React

### ISSUE THREAD

**Issue by hanayashiki** [JedWatson/classnames#226]
Every time to specify multiple classes i need to write the long "className(...)" to get this basic yet convenient utility. This does not conflict current react typings and should work with current code perfectly

**Comment by rapritchard** [comment]
Pretty sure this project is dead, so unlikely to happen.

**Comment by hanayashiki** [comment]
so clsx is alive?

**Comment by JedWatson** [comment]
Funny story: way back in 2015, I had this library, and React shipped a similar (but more limited) utility.

The React team wanted to **unbundle** their utility because of all the support request it generated, so they pointed the react docs here and ✨ hey presto, classnames became one of the most downloaded packages in the ecosystem.

So I doubt at this point they're going to merge it back in.

Over the last few years it's basically been working really well, and with the sheer number of users I've been almost afraid to touch it. But interest has definitely surged lately and so I'm looking at how to modernise it, including **maybe** we can do something clever to make it "feel" built in (similar to how css-in-js libraries work)

That's all experimental at the moment, but I just wanted to let you know that it's not dead (or at least it's being brought out of hibernation) and will be updated in the near future with some performance and bundling improvements at a minimum.
