### ISSUE TITLE
Add a full example in readme

### ISSUE THREAD

**Issue by busla** [JedWatson/classnames#43]
I´m new to React and can´t figure out how to use this lib. Is there a possiblity that you could add a full example to the README where state is manipulated to generate classes on a form with multiple inputs?

Thanks.

**Comment by JedWatson** [comment]
@busla sorry for the delayed response, I somehow missed the notification. I'm guessing because this issue is a month old you've worked it out by now?

Usage is actually sort-of covered in the React docs: https://facebook.github.io/react/docs/class-name-manipulation.html

I'm happy to expand on usage in the Readme, can you give us a better guide on exactly what would help you though?

**Comment by busla** [comment]
@JedWatson thanks for replying. Well, I started using react-bootstrap for the project but no, I didn´t resolve the issue. I´m sure it was related to my noobness with React at the time :-)

**Comment by rohanthacker** [comment]
@JedWatson  Just a heads up.  The link on the github page now shows a deprecated note and a link to the package.

**Comment by JedWatson** [comment]
@rohanthacker good point. I'll add some more examples :)
